using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using AutoMapper;
using Vidli.Dtos;
using Vidli.Models;

namespace Vidli.Controllers.Api
{
    public class CustomersController : ApiController
    {
        //application dbcontext for accessing db
        private ApplicationDbContext _context;

        //intiialize it
        public CustomersController()
        {
            _context = new ApplicationDbContext();
        }

        //as we return a list of object i.e customer by convention it will resoponse to 
        //GET/api/customer
        public IEnumerable<CustomerDto> GetCustomers()
        {
            //return the list of customer from Customers table in db
            return _context.Customers.ToList().Select(Mapper.Map<Customer, CustomerDto>); //using select, for mapping and referncing
        }

        public IHttpActionResult GetCustomer(int id) //usning IHttpActionResult
        {
            var customer = _context.Customers.SingleOrDefault(c => c.Id == id);

            //if customer is not found 
            if (customer == null)
                return NotFound();

            //return Mapper.Map<Customer, CustomerDto>(customer);
            return Ok(Mapper.Map<Customer, CustomerDto>(customer));
        }

        //create a customer: when we create a resource we return that to client
        //POST /api/customers
        [HttpPost]
        public IHttpActionResult CreateCustomer(CustomerDto customerDto) //use IHttpAction.. which has several helper method
        {
            //if not valid
            if (!ModelState.IsValid)
                //throw new HttpResponseException(HttpStatusCode.BadRequest);
                //instead of throw exception we can use helper method as below
                return BadRequest();

            //create a customer object
            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            //otherwise add the changes to Customers table context and save the changes
            _context.Customers.Add(customer);

            _context.SaveChanges();

            //this customer object has an Id that generated by db not by form, and need to add this id to dto
            customerDto.Id = customer.Id;
            //return created and also pas URI - Inified resource identifier 
            //the uri should have: api/cusotmers/id
            //for the second arg we need to pass the actual obeject that was createdd i.e. is customerDto
            return Created(new Uri(Request.RequestUri + "/" + customer.Id), customerDto);
        }

        //for update we use PUT and it can return a customer or void
        //the url is like: PUT/api/customers/id
        //id form url to get the customer from db and customer from request body i.e. the updated info
        [HttpPut]
        public void UpdateCustomer(int id, CustomerDto customerDto) 
        {
            //if request is not valid
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            //get the customer from db
            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);

            //if customer is not found 
            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            //map cusotmer to dto, and also need to pass the second arg i.e. customerInDb to load it in form
            Mapper.Map<CustomerDto, Customer>(customerDto, customerInDb);


            //save the chagnes to context
            _context.SaveChanges();

        }

        //for Delete
        //DELETE /api/customers/id
        [HttpDelete]
        public void DeleteCustomer(int id)
        {
            //get the customer from db
            var customerInDb = _context.Customers.SingleOrDefault(c => c.Id == id);

            //if customer is not found 
            if (customerInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            //remove customer from db
            _context.Customers.Remove(customerInDb);
            _context.SaveChanges();
        }


    }
}
