// <auto-generated />
namespace Vidli.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddGenerPopulate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGenerPopulate));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091824595_AddGenerPopulate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
